ignoreWorkspaceRootCheck: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - playground
  - docs
  - packages/*
  - examples/*

onlyBuiltDependencies:
  - esbuild
  - rolldown
  - simple-git-hooks
